# Generated by Django 2.0.7 on 2018-07-16 22:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=43, unique=True)),
                ('display', models.CharField(default='', max_length=24)),
                ('is_contract', models.BooleanField(default=False, editable=False, verbose_name='contract?')),
                ('code', models.TextField(default='', editable=False)),
                ('balance', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=18)),
                ('app_only', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66, unique=True)),
                ('num_txs', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('tps', models.IntegerField(default=0)),
                ('difficulty', models.BigIntegerField(default=0)),
                ('nonce', models.CharField(default='', max_length=20)),
                ('timestamp', models.IntegerField(default=0)),
                ('date', models.DateField(default=None, editable=False, null=True)),
                ('miner', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='moac.Address', verbose_name='minerpool')),
            ],
            options={
                'verbose_name': 'ledger',
                'verbose_name_plural': 'ledgers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StatLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, unique=True)),
                ('ledger_tps', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_tps', to='moac.Ledger')),
                ('ledger_txs', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_txs', to='moac.Ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(default='token name', max_length=64)),
                ('decimals', models.IntegerField(default=0)),
                ('total_supply', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=30)),
                ('address', models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moac.Address')),
                ('owners', models.ManyToManyField(editable=False, related_name='owners', to='moac.Address')),
                ('token_type', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.TokenType')),
            ],
        ),
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(default=0)),
                ('address', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='moac.Address')),
                ('block', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='moac.Ledger')),
                ('topic', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.TokenTopic')),
            ],
            options={
                'ordering': ('-block', '-transaction', '-index'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('nonce', models.BigIntegerField(default=0)),
                ('value', models.BigIntegerField(default=0, verbose_name='value int')),
                ('value_moac', models.DecimalField(decimal_places=9, default=Decimal('0'), editable=False, max_digits=18, verbose_name='value')),
                ('index', models.IntegerField(default=0)),
                ('ledger', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='moac.Ledger')),
                ('tx_from', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tx_from', to='moac.Address')),
                ('tx_to', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tx_to', to='moac.Address')),
            ],
            options={
                'ordering': ('ledger', 'index'),
            },
        ),
        migrations.CreateModel(
            name='Uncle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66)),
                ('number', models.IntegerField(default=0, verbose_name='hight')),
                ('ledger', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='moac.Ledger')),
                ('miner', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='moac.Address')),
            ],
            options={
                'ordering': ('ledger',),
            },
        ),
        migrations.AddField(
            model_name='tokenlog',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='moac.Transaction'),
        ),
        migrations.AddField(
            model_name='tokenlog',
            name='wallets',
            field=models.ManyToManyField(related_name='wallets', to='moac.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='uncle',
            unique_together={('hash', 'ledger')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('ledger', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='tokenlog',
            unique_together={('block', 'transaction', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('symbol', 'token_type', 'address')},
        ),
    ]
