# Generated by Django 2.0.6 on 2018-06-30 19:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonJingtumLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('parent_hash', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('synced', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='JsonMoacLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=66, unique=True)),
                ('parent_hash', models.CharField(default='', editable=False, max_length=66, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('synced', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='JsonMoacUncle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=66)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('synced', models.BooleanField(default=False, editable=False)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonstore.JsonMoacLedger')),
            ],
            options={
                'ordering': ('ledger',),
            },
        ),
        migrations.CreateModel(
            name='JsonStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=16, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jsonmoacuncle',
            unique_together={('hash', 'ledger')},
        ),
    ]
